#ifndef QUELLOG_ZECTRIX_CONFIG_H_
#define QUELLOG_ZECTRIX_CONFIG_H_

#include <driver/gpio.h>

#define QUELLOG_BOOT_BUTTON_GPIO GPIO_NUM_0
#define QUELLOG_UP_BUTTON_GPIO GPIO_NUM_39
#define QUELLOG_DOWN_BUTTON_GPIO GPIO_NUM_18
#define QUELLOG_DISPLAY_WIDTH 400
#define QUELLOG_DISPLAY_HEIGHT 300
#define QUELLOG_EPD_SPI_HOST SPI3_HOST
#define QUELLOG_EPD_DC_GPIO GPIO_NUM_10
#define QUELLOG_EPD_CS_GPIO GPIO_NUM_11
#define QUELLOG_EPD_SCK_GPIO GPIO_NUM_12
#define QUELLOG_EPD_MOSI_GPIO GPIO_NUM_13
#define QUELLOG_EPD_RST_GPIO GPIO_NUM_9
#define QUELLOG_EPD_BUSY_GPIO GPIO_NUM_8
#define QUELLOG_EPD_POWER_GPIO GPIO_NUM_6
#define QUELLOG_BATTERY_POWER_GPIO GPIO_NUM_17
#define QUELLOG_BATTERY_POWER_READY_GPIO GPIO_NUM_18
#define QUELLOG_BATTERY_ADC_CHANNEL ADC_CHANNEL_3
#define QUELLOG_CHARGE_DETECT_GPIO GPIO_NUM_2
#define QUELLOG_CHARGE_FULL_GPIO GPIO_NUM_1
#define CHARGE_DETECT_CHARGING_LEVEL 0

#endif  // QUELLOG_ZECTRIX_CONFIG_H_
