set(SOURCES
    "main.cc"
    "application.cc"
    "settings.cc"
    "boards/common/board.cc"
    "boards/zectrix-s3-epaper-4.2/charge_status.cc"
    "boards/zectrix-s3-epaper-4.2/zectrix-s3-epaper-4.2.cc"
    "display/display.cc"
    "display/lvgl_text_renderer.cc"
    "display/top_status_bar.cc"
    "display/ui_page_registry.cc"
    "display/fonts/SourceHanSansSC_Medium_slim.c"
    "display/fonts/SourceHanSansSC_Regular_slim.c"
    "display/pages/recent_records_page.cc"
    "display/pages/settings_page.cc"
    "display/pages/stats_page.cc"
)

idf_component_register(
    SRCS ${SOURCES}
    INCLUDE_DIRS
        "."
        "boards/common"
        "display"
        "display/pages"
    REQUIRES
        driver
        esp_adc
        esp_app_format
        esp_timer
        lvgl
        nvs_flash
        quellog_wifi
)

target_compile_definitions(
    ${COMPONENT_LIB}
    PRIVATE
    BOARD_NAME=\"zectrix-s3-epaper-4.2\"
    LV_LVGL_H_INCLUDE_SIMPLE
)
